server {
    listen 443 ssl;
    server_name example.com;
    server_tokens on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    autoindex on;

    location / {
        proxy_pass http://app_backend;
    }
}
